name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Directory Structure
        id: check-directory-structure
        run: |
          EXPECTED_STRUCTURE=(
            "*/conways_grid_output/output_0.npy"
            "*/conways_grid_output/output_1.npy"
            "*/conways_grid_output/output_2.npy"
            "*/plots/fractal_tree.png"
            "*/plots/julia.png"
            "*/plots/julia_grid.png"
            "*/plots/mandelbrot.png"
            "conways_grid_initial/grid_0.npy"
            "conways_grid_initial/grid_1.npy"
            "conways_grid_initial/grid_2.npy"
            "fractal_init.json"
            "main.ipynb"
          )

          all_exist=true

          echo "Checking directory structure..."

          for file in "${EXPECTED_STRUCTURE[@]}"; do
              if ! find . -path "./$file" -print -quit | grep -q .; then
                  echo "Missing: $file"
                  all_exist=false
              fi
          done

          if [[ ! -e "README.txt" && ! -e "README.md" ]]; then
            echo "Missing: README.txt or README.md"
            all_exist=false
          fi

          if $all_exist; then
            echo "Directory structure is correct."
            echo "SUCCESS! :)"
            exit 0
          else
            echo "Directory structure is incorrect / files are missing. See missing files above."
            echo "FAILED! :("
            exit 1
          fi