SELECT E.Fname AS Manager_Fname, E.Lname AS Manager_Lname
FROM DEPARTMENT D
JOIN EMPLOYEE E ON D.Mgr_ssn = E.Ssn
WHERE D.Dnumber = (SELECT Dno FROM EMPLOYEE GROUP BY Dno ORDER BY COUNT(*) DESC LIMIT 1);
