name: Autograding Tests

on:
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Directory Structure
        id: check-directory-structure
        run: |
          EXPECTED_STRUCTURE=(
            src/
          )
          
          all_exist=true

          echo "Checking directory structure..."

          for path in "${EXPECTED_STRUCTURE[@]}"; do
            if [[ ! -e $path ]]; then
              echo "Missing: $path"
              all_exist=false
            fi
          done

          if [[ ! -e "README.txt" && ! -e "README.md" ]]; then
            echo "Missing: README.txt or README.md"
            all_exist=false
          fi

          if $all_exist; then
            echo "Directory structure is correct."
            echo "SUCCESS! GREAT JOB!"
            exit 0
          else
            echo "Directory structure is incorrect. See missing files above."
            echo "FAILED! Bruh.. check your directory structure with that uploaded on Teams."
            exit 1
          fi
